create table if not exists public.game_scores (
  id bigint generated by default as identity primary key,
  player_name text not null,
  score integer not null,
  created_at timestamptz not null default timezone('utc', now()),
  constraint game_scores_player_name_length
    check (char_length(btrim(player_name)) between 1 and 12),
  constraint game_scores_score_range
    check (score between 1 and 1000000)
);

create index if not exists game_scores_rank_idx
  on public.game_scores (score desc, created_at asc);

alter table public.game_scores enable row level security;

revoke all on table public.game_scores from anon, authenticated;
grant select (id, player_name, score, created_at)
  on table public.game_scores to anon, authenticated;
grant insert (player_name, score)
  on table public.game_scores to anon, authenticated;
grant usage, select on sequence public.game_scores_id_seq to anon, authenticated;

drop policy if exists "Public game scores are readable" on public.game_scores;
create policy "Public game scores are readable"
  on public.game_scores
  for select
  to anon, authenticated
  using (true);

drop policy if exists "Visitors can submit valid game scores" on public.game_scores;
create policy "Visitors can submit valid game scores"
  on public.game_scores
  for insert
  to anon, authenticated
  with check (
    char_length(btrim(player_name)) between 1 and 12
    and score between 1 and 1000000
  );
