create table if not exists public.site_comments (
  id bigint generated by default as identity primary key,
  page_key text not null,
  author text not null,
  content text not null,
  is_visible boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  constraint site_comments_page_key_length check (char_length(page_key) between 1 and 220),
  constraint site_comments_author_length check (char_length(btrim(author)) between 1 and 32),
  constraint site_comments_content_length check (char_length(btrim(content)) between 1 and 500)
);

create index if not exists site_comments_page_created_idx
  on public.site_comments (page_key, created_at desc)
  where is_visible = true;

alter table public.site_comments enable row level security;

revoke all on table public.site_comments from anon, authenticated;
grant select (id, page_key, author, content, created_at)
  on table public.site_comments to anon, authenticated;
grant insert (page_key, author, content)
  on table public.site_comments to anon, authenticated;
grant usage, select on sequence public.site_comments_id_seq to anon, authenticated;

drop policy if exists "Public comments are readable" on public.site_comments;
create policy "Public comments are readable"
  on public.site_comments
  for select
  to anon, authenticated
  using (is_visible = true);

drop policy if exists "Visitors can create valid comments" on public.site_comments;
create policy "Visitors can create valid comments"
  on public.site_comments
  for insert
  to anon, authenticated
  with check (
    is_visible = true
    and char_length(page_key) between 1 and 220
    and char_length(btrim(author)) between 1 and 32
    and char_length(btrim(content)) between 1 and 500
  );
